[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/places"
  to = "/places.html"
  status = 200

[[redirects]]
  from = "/place/shat-gombuj-mosque"
  to = "/place_shatgombuj.html"
  status = 200

[[redirects]]
  from = "/place/somapura-mahavihara"
  to = "/place_somapura.html"
  status = 200

[[redirects]]
  from = "/place/lalbagh-fort"
  to = "/place_lalbagh.html"
  status = 200

[[redirects]]
  from = "/place/ahsan-manzil"
  to = "/place_ahsan.html"
  status = 200

[[redirects]]
  from = "/place/mahasthangarh"
  to = "/place_mahasthan.html"
  status = 200

[[redirects]]
  from = "/place/mainamati"
  to = "/place_mainamati.html"
  status = 200

[[redirects]]
  from = "/place/kantajew-temple"
  to = "/place_kantajew.html"
  status = 200

[[redirects]]
  from = "/place/panam-city"
  to = "/place_panam.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
